services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dicom_db
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "mysql -u root -ppassword -D dicom_db -e 'SELECT 1;'"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  node-backend:
    build: ./backend
    volumes:
      - uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${NODE_PORT}:4000" 
    command: sh -c "sleep 15 && node server.js"
    networks:
      - app-network
  python-service:
    build:
      context: ./pydicom
    volumes:
      - uploads:/app/uploads
    ports:
      - "${PYTHON_PORT}:5000"
    networks:
      - app-network
      
  react-frontend:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "${FRONTEND_PORT}:3000"  
    depends_on:
      - node-backend
    environment:
      - VITE_API_URL=http://localhost:${NODE_PORT}
    networks:
      - app-network

volumes:
  uploads:  
    driver: local

networks:
  app-network:
    driver: bridge

